### ISSUE TITLE
Apple-Pay-Signature-Verification

### ISSUE THREAD

**Issue by Cris464** [zooz-mobile/Apple-Pay-Signature-Verification#4]
Hi,
i am almost done with the code implementation. but i am facing this issue .Can you please advice me on this exception.

Thanks in advance.

<exceptionClassName>java.lang.NoSuchFieldError</exceptionClassName>
            <exceptionMessage>dsa_with_sha224 at org.bouncycastle.cms.CMSSignedHelper.&lt;clinit>(Unknown Source)</exceptionMessage>

**Comment by zooz-mobile** [comment]
Which version of bcprov and bcmail do you use?

**Comment by Cris464** [comment]
bcmail-jdk16-146.jar
bcprov-jdk16-146.jar

Please advice.

**Comment by zooz-mobile** [comment]
Looks fine.
I didn't encounter such error.

If you run the github project does it work?

Do you use webserver? glassfish, jboss? to run your application?

**Comment by zooz-mobile** [comment]
Issue closed as no response from issue opener.

**Comment by abhimanyuvarma** [comment]
I am also getting the same issue - when you try to run the main class when i run the github project on my local box . Has anybody figured the issue ?

**Comment by Cris464** [comment]
abhimanyu varma , can you please  share your  stack trace....

**Comment by abhimanyuvarma** [comment]
I found the issue - it was jar conflict issue - an older version in the dependency tree was creating that problem
Thanks
